local colors = {
  green          = '#9bce52',
  orange         = '#ff9100',
  red            = '#e0425f',
  darker_blue    = '#256991',
  dark_blue      = '#3a87af',
  light_blue     = '#88d3f5',
  white          = '#ffffff',
  lightest_grey  = '#bcbcbc',
  dark_grey      = '#444444',
  darkest_grey   = '#262626',
  light_grey     = '#6c6c6c',
  grey           = '#585858',
  darker_grey    = '#303030',
  black          = '#1c1c1c',
}

return {
  normal = {
    a = { fg = colors.darkest_grey, bg = colors.green, gui = 'bold' },
    b = { fg = colors.lightest_grey, bg = colors.grey },
    c = { fg = colors.lightest_grey, bg = colors.darker_grey },
    x = { fg = colors.lightest_grey, bg = colors.darker_grey },
    y = { fg = colors.lightest_grey, bg = colors.grey },
    z = { fg = colors.darker_grey, bg = colors.lightest_grey },
  },
  insert = {
    a = { fg = colors.darkest_grey, bg = colors.light_blue, gui = 'bold' },
    b = { fg = colors.lightest_grey, bg = colors.grey },
    c = { fg = colors.lightest_grey, bg = colors.darker_grey },
    x = { fg = colors.lightest_grey, bg = colors.darker_grey },
    y = { fg = colors.lightest_grey, bg = colors.grey },
    z = { fg = colors.darker_grey, bg = colors.lightest_grey },
  },
  visual = {
    a = { fg = colors.darkest_grey, bg = colors.orange, gui = 'bold' },
    b = { fg = colors.lightest_grey, bg = colors.grey },
    c = { fg = colors.lightest_grey, bg = colors.darker_grey },
    x = { fg = colors.lightest_grey, bg = colors.darker_grey },
    y = { fg = colors.lightest_grey, bg = colors.grey },
    z = { fg = colors.darker_grey, bg = colors.lightest_grey },
  },
  replace = {
    a = { fg = colors.white, bg = colors.red, gui = 'bold' },
    b = { fg = colors.lightest_grey, bg = colors.grey },
    c = { fg = colors.lightest_grey, bg = colors.darker_grey },
    x = { fg = colors.lightest_grey, bg = colors.darker_grey },
    y = { fg = colors.lightest_grey, bg = colors.grey },
    z = { fg = colors.darker_grey, bg = colors.lightest_grey },
  },
  inactive = {
    a = { fg = colors.lightest_grey, bg = colors.darker_grey },
    b = { fg = colors.lightest_grey, bg = colors.darker_grey },
    c = { fg = colors.lightest_grey, bg = colors.darker_grey },
    x = { fg = colors.lightest_grey, bg = colors.darker_grey },
    y = { fg = colors.lightest_grey, bg = colors.darker_grey },
    z = { fg = colors.light_grey, bg = colors.dark_grey },
  },
}
