#!/usr/bin/env perl

# Modified version of:
# https://github.com/vivien/i3blocks-contrib/tree/master/battery
# Copyright 2014 Pierre Mavro <deimos@deimos.fr>
# Copyright 2014 Vivien Didelot <vivien@didelot.org>
# Licensed under the terms of the GNU GPL v3, or any later version.

###########################
# BAT BLOCK
###########################

use strict;
use warnings;
use utf8;

my $text;
my $acpi;
my $status;
my $percent;
my $ac_adapt;

# Read the first line of the "acpi" command output
open (ACPI, "acpi -b 2>/dev/null| grep 'Battery 0' |") or die;
$acpi = <ACPI>;
close(ACPI);

# Fail on unexpected output
if (not defined($acpi)) {
    # Don't print anything to stderr if there is no battery
    exit(0);
}
elsif ($acpi !~ /: ([\w\s]+), (\d+)%/) {
	die "$acpi\n";
}

$status = $1;
$percent = $2;

# Format text
$text = "BAT: $percent%";
if ($status eq 'Charging') {
	$text .= ' (CHR)';
} elsif ($status eq 'Unknown') {
	open (AC_ADAPTER, "acpi -a |") or die;
	$ac_adapt = <AC_ADAPTER>;
	close(AC_ADAPTER);
	if ($ac_adapt =~ /: ([\w-]+)/) {
		$ac_adapt = $1;
		if ($ac_adapt eq 'on-line') {
			$text .= ' (CHR)';
	
        }
    }
}

# Hide block when fully charged
if ($percent > 95) {
    $text = "";
}

# Print long text
print "$text\n";

# Print short text
print "$text\n";

# Print color when low battery (and logout when critical) 
if ($status eq 'Discharging') {
	if ($percent < 30) {
		print "$ENV{I3BLOCK_WARN_COLOR}\n";
    }
	if ($percent < 5) {
		exit(33);
	}
}

exit(0);
