#!/bin/bash

INFO_CMUS=$(cmus-remote -Q 2>/dev/null)

if [[ $? -eq 0 ]]; then
  INFO_TITLE=$(echo "${INFO_CMUS}" | sed -n -e 's/^.*title//p' | head -n 1)
  INFO_ALBUM=$(echo "${INFO_CMUS}" | sed -n -e 's/^.*album//p' | head -n 1)
  INFO_ARTIST=$(echo "${INFO_CMUS}" | sed -n -e 's/^.*artist//p' | head -n 1)
else
  exit
fi

if [[ "${INFO_ARTIST}" ]] && [[ "${INFO_TITLE}" ]]; then
  OUT_TEXT="${INFO_ARTIST} - ${INFO_TITLE}"
elif [[ "${INFO_TITLE}" ]]; then
  OUT_TEXT="${INFO_TITLE}"
fi

# Handle muse input
case "$BLOCK_BUTTON" in
    1) cmus-remote --pause ;;
    3) cmus-remote --stop ;;
    4) cmus-remote --prev ;;
    5) cmus-remote --next ;;
esac

echo "CMUS: ${OUT_TEXT}"
echo "CMUS: ${OUT_TEXT}"

exit