#!/bin/bash
volume_mute=$(amixer sget Master | awk -F"[][]" '/dB/ { print $6 }');volume=$(amixer sget Master | awk -F"[][]" '/dB/ { print $2 }');if [ "$volume_mute" == "off" ];then echo "-";else echo $volume;fi
case $BLOCK_BUTTON in 1) amixer -q sset Master toggle ;;4) amixer -q sset Master 1+ unmute ;;5) amixer -q sset Master 1- unmute ;;esac
