worker_processes  2;

events { worker_connections  1024; }

http {
    charset                 utf-8;
    sendfile                on;
    tcp_nopush              on;
    tcp_nodelay             on;
    keepalive_timeout       65;
    types_hash_max_size     4096;
    include                 mime.types;
    default_type            application/octet-stream;
    access_log              /var/log/nginx/access.log;
    error_log               /var/log/nginx/error.log warn;

    # default server
    server {
        listen              80 default_server;
        server_name         _;
        return              301 https://<domain1>$request_uri;
    }

    # test server (only accessable on the local network)
    server {
        listen              1337;
        root                /home/lzzrhx/html/test;
    }

    # <domain1>
    server {
        server_name         <domain1> www.<domain1>;
        listen              80;
        return              301 https://<domain1>$request_uri;
    }
    server {
        server_name         www.<domain1>;
        listen              443 ssl;
        return              301 https://<domain1>$request_uri;
        # SSL cert
        ssl_certificate     /etc/letsencrypt/live/<domain1>/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/<domain1>/privkey.pem;
        include             /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;
    }
    server {
        server_name         <domain1>;
        listen              443 ssl;
        root                /home/lzzrhx/html/<domain1>;
        access_log          /var/log/nginx/<domain1>.log;
        # SSL cert
        ssl_certificate     /etc/letsencrypt/live/<domain1>/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/<domain1>/privkey.pem;
        include             /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;
    }

    # <domain2>
    server {
        server_name         <domain2> www.<domain2>;
        listen              80;
        return              301 https://<domain2>$request_uri;
    }
    server {
        server_name         www.<domain2>;
        listen              443 ssl;
        return              301 https://<domain2>$request_uri;
        # SSL cert
        ssl_certificate     /etc/letsencrypt/live/<domain2>/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/<domain2>/privkey.pem;
        include             /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;
    }
    server {
        server_name         <domain2>;
        listen              443 ssl;
        root                /home/lzzrhx/html/<domain2>;
        access_log          /var/log/nginx/<domain2>.log;
        # SSL cert
        ssl_certificate     /etc/letsencrypt/live/<domain2>/fullchain.pem;
        ssl_certificate_key /etc/letsencrypt/live/<domain2>/privkey.pem;
        include             /etc/letsencrypt/options-ssl-nginx.conf;
        ssl_dhparam         /etc/letsencrypt/ssl-dhparams.pem;
    }
}
